---
- hosts: 192.168.0.1
  connection: local
  gather_facts: no
  collections:
    - a10.acos_axapi

  vars:
    ansible_host: "192.168.0.1"
  tasks:
  - name: Configure real server
    a10_slb_server:
      ansible_host: "{{ ansible_host }}"
      ansible_port: "{{ ansible_port }}"
      ansible_username: "{{ ansible_username }}"
      ansible_password: "{{ ansible_password }}"
      name: "{{ item.name }}"
      host: "{{ item.host }}"
      port_list:
        - port_number: "{{ item.port_number }}"
          protocol: "{{ item.protocol }}"
      state: present
    with_items:
      - { name: "s1", host: "10.0.2.11", port_number: 80, protocol: "tcp" }
      - { name: "s2", host: "10.0.2.12", port_number: 80, protocol: "tcp" }

  - name: Write memory
    a10_write_memory:
      ansible_host: "{{ ansible_host }}"
      ansible_port: "{{ ansible_port }}"
      ansible_username: "{{ ansible_username }}"
      ansible_password: "{{ ansible_password }}"
      state: present
      partition: all
