---
- hosts: 192.168.0.1
  connection: local
  gather_facts: no
  collections:
    - a10.acos_axapi

  vars:
    ansible_host: "192.168.0.1"
  tasks:
  - name: Import cert file
    a10_import:
      ansible_host: "{{ ansible_host }}"
      ansible_port: "{{ ansible_port }}"
      ansible_username: "{{ ansible_username }}"
      ansible_password: "{{ ansible_password }}"
      ssl_cert: "server.crt"
      use_mgmt_port: True
      overwrite: True
      remote_file: "sftp://root@192.168.0.101/root/certs/server.crt"
      password: "a10"
      state: present

  - name: Import key
    a10_import:
      ansible_host: "{{ ansible_host }}"
      ansible_port: "{{ ansible_port }}"
      ansible_username: "{{ ansible_username }}"
      ansible_password: "{{ ansible_password }}"
      ssl_key: "server.key"
      use_mgmt_port: True
      overwrite: True
      remote_file: "sftp://root@192.168.0.101/root/certs/server.key"
      password: "a10"
      state: present
