---
- hosts: 192.168.0.1
  connection: local
  gather_facts: no
  become: True
  collections:
    - a10.acos_cli

  tasks:
    - name: Enable Interface Ethernet
      acos_command:
        commands:
          - command: "configure"
          - command: "interface ethernet 1"
          - command: "enable"
          - command: "exit"
          - command: "interface ethernet 2"
          - command: "enable"
          - command: "exit"
          - command: "write memory all-partitions"
